services:
  campus-schnitzeljagd:
    image: ghcr.io/peherebe/campus-schnitzeljagd:latest
    restart: always
    environment:
      - TRUSTED_PROXY_IPS=134.169.82.149
    ports:
      - "8080:8080"
    volumes:
      - campus_data:/data

volumes:
  campus_data:
    name: campus_data
